# Generated by Django 5.2.10 on 2026-01-17 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0002_expenses"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Expenses",
            new_name="Expense",
        ),
    ]
